#!/bin/sh
MDCE_DECODE_FUNCTION=parallel.cluster.generic.independentDecodeFcn
export MDCE_DECODE_FUNCTION
MDCE_STORAGE_CONSTRUCTOR=makeFileStorageObject
export MDCE_STORAGE_CONSTRUCTOR
MDCE_JOB_LOCATION=Job5
export MDCE_JOB_LOCATION
MDCE_MATLAB_EXE=/shared/MATLAB/R2018a/bin/worker
export MDCE_MATLAB_EXE
MDCE_DEBUG=true
export MDCE_DEBUG
MLM_WEB_LICENSE=false
export MLM_WEB_LICENSE
MDCE_STORAGE_LOCATION=/home/vkanoria/Somewhere on the Turing Cluster/vkanoria/R2018a
export MDCE_STORAGE_LOCATION
MDCE_TASK_LOCATION=Job5/Task1
export MDCE_TASK_LOCATION
qsub -N Job5.1 -j oe -o '/home/vkanoria/Somewhere on the Turing Cluster/vkanoria/R2018a/Job5/Task1.log' -v MDCE_DECODE_FUNCTION,MDCE_STORAGE_CONSTRUCTOR,MDCE_JOB_LOCATION,MDCE_MATLAB_EXE,MDCE_DEBUG,MLM_WEB_LICENSE,MDCE_STORAGE_LOCATION,MDCE_TASK_LOCATION  '/home/vkanoria/Somewhere on the Turing Cluster/vkanoria/R2018a/Job5/independentJobWrapper.sh'
